#!/usr/bin/env python3
"""Genera uno scheletro di rule_matrix.yaml a partire da PAI_CODE_INVENTORY.csv.

Il CSV in genere è UTF-16 e può avere un preambolo (SQL) prima dell'header.
Questo script trova l'header e usa solo i record.

Uso:
  python scripts/gen_rule_matrix_from_inventory.py PAI_CODE_INVENTORY.csv rules/rule_matrix.generated.yaml
"""

import sys
import csv
from collections import defaultdict

def norm(s: str) -> str:
    return (str(s) if s is not None else "").strip().upper()

def infer_basin(table: str) -> str:
    t = (table or "").lower()
    if t.startswith("pai_"):
        head = t.split("__", 1)[0]
        if "_" in head:
            return head.split("_", 1)[1].capitalize()
    return "Unknown"

def infer_studio(table: str) -> str:
    t = (table or "").lower()
    if "frana" in t:
        return "idrogeologico"
    return "idraulico"

def main(inp, outp):
    with open(inp, "rb") as f:
        raw = f.read()

    # Try UTF-16 then UTF-8
    for enc in ("utf-16", "utf-8"):
        try:
            text = raw.decode(enc)
            break
        except Exception:
            text = None
    if text is None:
        raise SystemExit("Impossibile decodificare il file (provato utf-16/utf-8).")

    lines = text.splitlines()
    header = "table_name,column_name,raw_value,norm_value,n"
    try:
        i0 = next(i for i,l in enumerate(lines) if l.strip() == header)
    except StopIteration:
        raise SystemExit(f"Header non trovato. Atteso: {header}")

    rdr = csv.DictReader(lines[i0:])
    data = defaultdict(lambda: defaultdict(list))  # table -> column -> (raw,n)
    for r in rdr:
        t = (r.get("table_name") or "").strip()
        c = (r.get("column_name") or "").strip()
        rawv = r.get("raw_value")
        n = int(r.get("n") or "0")
        if not t or not c:
            continue
        if rawv is None or str(rawv).strip() == "":
            continue
        data[t][c].append((str(rawv), n))

    # choose class column = max distinct values
    class_col = {}
    for t, cols in data.items():
        best = None
        best_k = -1
        for c, vals in cols.items():
            k = len(vals)
            if k > best_k:
                best_k = k
                best = c
        class_col[t] = best or ""

    out = []
    out.append("# AUTOGENERATED. Compila template/normativa e (se serve) correggi class_col.")
    out.append("tables:")
    for t in sorted(data.keys()):
        out.append(f"  {t}:")
        out.append(f"    bacino: {infer_basin(t)}")
        out.append(f"    studio: {infer_studio(t)}")
        out.append(f"    class_col: {class_col[t]}")
        out.append("    codes:")

        chosen = class_col[t]
        vals = sorted(data[t].get(chosen, []), key=lambda x: (-x[1], norm(x[0])))
        for rawv, n in vals:
            key = norm(rawv)
            out.append(f"      "{key}":")
            out.append(f"        count: {n}")
            out.append(f"        template: null")
            out.append(f"        normativa: null")

    with open(outp, "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")
    print(f"Wrote {outp} for {len(data)} tables.")

if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: gen_rule_matrix_from_inventory.py <PAI_CODE_INVENTORY.csv> <out.yaml>")
        sys.exit(2)
    main(sys.argv[1], sys.argv[2])
